// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type QueryRecordsRequest struct {
	// Tenant Id
	DataPartitionID string                  `header:"style=simple,explode=false,name=data-partition-id"`
	QueryRequest    components.QueryRequest `request:"mediaType=application/json"`
}

func (o *QueryRecordsRequest) GetDataPartitionID() string {
	if o == nil {
		return ""
	}
	return o.DataPartitionID
}

func (o *QueryRecordsRequest) GetQueryRequest() components.QueryRequest {
	if o == nil {
		return components.QueryRequest{}
	}
	return o.QueryRequest
}

type QueryRecordsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (o *QueryRecordsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *QueryRecordsResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}
