// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type QueryWithCursorRequest struct {
	// Tenant Id
	DataPartitionID    string                        `header:"style=simple,explode=false,name=data-partition-id"`
	CursorQueryRequest components.CursorQueryRequest `request:"mediaType=application/json"`
}

func (o *QueryWithCursorRequest) GetDataPartitionID() string {
	if o == nil {
		return ""
	}
	return o.DataPartitionID
}

func (o *QueryWithCursorRequest) GetCursorQueryRequest() components.CursorQueryRequest {
	if o == nil {
		return components.CursorQueryRequest{}
	}
	return o.CursorQueryRequest
}

type QueryWithCursorResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (o *QueryWithCursorResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *QueryWithCursorResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}
