// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AggregationResponse struct {
	Key   *string
	Count *int64
}

func (o *AggregationResponse) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *AggregationResponse) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}
