// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ByBoundingBox struct {
	TopLeft     Point `json:"topLeft"`
	BottomRight Point `json:"bottomRight"`
}

func (o *ByBoundingBox) GetTopLeft() Point {
	if o == nil {
		return Point{}
	}
	return o.TopLeft
}

func (o *ByBoundingBox) GetBottomRight() Point {
	if o == nil {
		return Point{}
	}
	return o.BottomRight
}
