// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ByDistance struct {
	Distance *float64 `json:"distance,omitempty"`
	Point    Point    `json:"point"`
}

func (o *ByDistance) GetDistance() *float64 {
	if o == nil {
		return nil
	}
	return o.Distance
}

func (o *ByDistance) GetPoint() Point {
	if o == nil {
		return Point{}
	}
	return o.Point
}
