// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ByIntersection struct {
	Polygons []Polygon `json:"polygons"`
}

func (o *ByIntersection) GetPolygons() []Polygon {
	if o == nil {
		return []Polygon{}
	}
	return o.Polygons
}
