// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Results struct {
}

type CursorQueryResponse struct {
	Cursor     *string
	Results    []map[string]Results
	TotalCount *int64
}

func (o *CursorQueryResponse) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *CursorQueryResponse) GetResults() []map[string]Results {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *CursorQueryResponse) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}
