// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Kind struct {
}

type CursorQueryRequest struct {
	Kind            Kind           `json:"kind"`
	Limit           *int           `json:"limit,omitempty"`
	Query           *string        `json:"query,omitempty"`
	ReturnedFields  []string       `json:"returnedFields,omitempty"`
	Sort            *SortQuery     `json:"sort,omitempty"`
	QueryAsOwner    *bool          `json:"queryAsOwner,omitempty"`
	TrackTotalCount *bool          `json:"trackTotalCount,omitempty"`
	SpatialFilter   *SpatialFilter `json:"spatialFilter,omitempty"`
	Cursor          *string        `json:"cursor,omitempty"`
}

func (o *CursorQueryRequest) GetKind() Kind {
	if o == nil {
		return Kind{}
	}
	return o.Kind
}

func (o *CursorQueryRequest) GetLimit() *int {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *CursorQueryRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *CursorQueryRequest) GetReturnedFields() []string {
	if o == nil {
		return nil
	}
	return o.ReturnedFields
}

func (o *CursorQueryRequest) GetSort() *SortQuery {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *CursorQueryRequest) GetQueryAsOwner() *bool {
	if o == nil {
		return nil
	}
	return o.QueryAsOwner
}

func (o *CursorQueryRequest) GetTrackTotalCount() *bool {
	if o == nil {
		return nil
	}
	return o.TrackTotalCount
}

func (o *CursorQueryRequest) GetSpatialFilter() *SpatialFilter {
	if o == nil {
		return nil
	}
	return o.SpatialFilter
}

func (o *CursorQueryRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}
