// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Point struct {
	Latitude  *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
}

func (o *Point) GetLatitude() *float64 {
	if o == nil {
		return nil
	}
	return o.Latitude
}

func (o *Point) GetLongitude() *float64 {
	if o == nil {
		return nil
	}
	return o.Longitude
}
