// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Polygon struct {
	Points []Point `json:"points,omitempty"`
}

func (o *Polygon) GetPoints() []Point {
	if o == nil {
		return nil
	}
	return o.Points
}
